################# Better Practice: keep service first

apiVersion: v1
kind: Service
metadata: 
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - port: 3000
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: firstdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template: 
#   kind: Pod      (bydefault)
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: salesforecast
          image: manujjoshi52/sales_forecasting

