apiVersion: v1
kind: Pod
metadata:
   name: "db-sql"
   labels: 
     app: db-sql
spec:
  containers: 
    - name: "db-sql"
      image: "mysql:5.7"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        - name: MYSQL_USER
          value: manuj
        - name: MYSQL_PASSWORD
          value: manuj
        - name:  MYSQL_DATABASE
          value: mydb     