apiVersion: v1
kind: ReplicationController
metadata: 
  name: demo-rc
spec:
  replicas: 1
  selector:
    app: webserver
  template: 
    metadata: 
      name: "http-pod"
      labels: 
        app: webserver
    spec: 
      containers:
        - name: "http-c1"
          image: "manujjoshi52/sales_forecasting:latest"

