apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessMode: ## can claim only one
    - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  hostPath: 
    path: /data
    type: DirectoryOrCreate
