apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJhY3Jha3Nkc3RlYW1ybmQuYXp1cmVjci5pbyI6IHsKCQkJImF1dGgiOiAiWVdOeVFXdHpSSE5VWldGdFVtNUVPbXhrTW01d2VHcG5SV0ZqTjFrMUt6aHZWVU5VTTBReE5tWm5kREppZVM5d1FqRnlVbVpaTW1reWJpdEJRMUpEY0UwME5FOD0iCgkJfQoJfQp9"
type: kubernetes.io/dockerconfigjson